<a href="https://colab.research.google.com/github/Orangeibro/kevincookiecompany.com/blob/main/PythonTest2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
my_array = np.array([3, 33, 333])

In [ ]:
print(my_array2)

[[11 12 13]
 [21 22 23]]


In [ ]:
print(my_array.shape)

(3,)


In [ ]:
print(my_array)

[ 3 33]


In [ ]:
print(my_array2)

[[11 12 13]
 [21 22 23]]


In [ ]:
print(my_array2[1,1],my_array2[0,0],my_array2[1,2])

22 11 23


In [ ]:
my_array[0]  = 13

In [ ]:
my_array2 =np.array([[11,12,13], [21,22,23]])

In [ ]:
Full2 = np.full([4,3], 9)

In [ ]:
print(Full2)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]


In [ ]:
ColIndices1 = np.array([0,1,2,3,4,0])

In [ ]:
RowIndices1 = np.arange(6)

In [ ]:
print(ColIndices1)

[0 1 2 3 4 0]


In [ ]:
print(RowIndices1)

[0 1 2 3 4 5]


In [ ]:
for row,col in zip(RowIndices1,ColIndices1):
  print(row, ' , ',col)

0  ,  0
1  ,  1
2  ,  2
3  ,  3
4  ,  4
5  ,  0


In [ ]:
my_array = np.array([[11,12,13,14,15,16],[21,22,23,24,25,26]
                    ,[31,32,33,34,35,36],[41,42,43,44,45,46]
                    ,[51,52,53,54,55,56],[61,62,63,64,65,66]])


In [ ]:
print(my_array)

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]
 [51 52 53 54 55 56]
 [61 62 63 64 65 66]]


In [ ]:
Mystring = 'HeLlO Workd!'

In [ ]:
Mystring

'HeLlO Workd!'

In [ ]:
len(Mystring)

12

In [ ]:
Mystring[0:len(Mystring):5]   #4 is the slice step size K

'H d'

In [ ]:
Quote1 = '#4 is the slice step size K'

In [ ]:
Quote1

'#4 is the slice step size K'

In [ ]:
Quote1.count('#')

1

In [ ]:
Quote1.find('the')

6

In [ ]:
Quote1.split()

['#4', 'is', 'the', 'slice', 'step', 'size', 'K']

In [ ]:
Quote2 = '   ' +'The number ' + Quote1

In [ ]:
Quote1

'#4 is the slice step size K'

In [ ]:
Quote2.strip()

'The number #4 is the slice step size K'

In [ ]:
Quote2 = Quote1.replace("#4 is", "Number 4 at")

In [ ]:
print(Quote2)

Number 4 at the slice step size K


In [ ]:
a =3
print(a+2.0, type(a+2.0))

5.0 <class 'float'>


In [ ]:
print(round(2.6), type(round(2.6)))

3 <class 'int'>


In [ ]:
print(not(4>3 and 100>6) ,type(not(4>3 and 100>6)))

True <class 'bool'>


In [ ]:
def hours_to_minutes(time_in_hours):
 '''converts time in hours to minutes'''
 Minutes = 60 * time_in_hours
 return Minutes


SyntaxError: ignored

In [ ]:
hours_to_minutes?

In [ ]:
def function1(fname):
  print(fname + " McCarthy")

In [ ]:
function1("Jay")

Jay McCarthy


In [ ]:
var = 'Panda'
if var =='Panda'
    print('Cute!'):
elif var =='Panda':
    print('Regal!')
else:
    print('Ugly...')

SyntaxError: ignored

In [ ]:
num = 0
while num <5:
    print(num, end=" ")
    num += 1
else:
 print("outside of loop")
    #break


0 1 2 3 4 outside of loop


In [ ]:
num = 10
while True:
    if num < 7:
        print('Breaking out of loop')
        break
        print(num)
        num -= 1
        print('Outside of loop')

KeyboardInterrupt: ignored

4
6
8
10
12
Goodbye!


In [ ]:
i = 0
while i <= 10:
    #########if i % 2 ==0:
        print(i)
        i = i + 2
##else:
print('  Goodbye!')

0
2
4
6
8
10
  Good bye!


In [ ]:
name = input('Enter your name: ')
while name =='':
  print('You did not enter your name')
  name = input('Enter your name: ')
  print(f'Hello {name}')

Enter your name: 
You did not enter your name
Enter your name: 
Hello 
You did not enter your name
Enter your name: 
Hello 
You did not enter your name
Enter your name: Orangeibro
Hello Orangeibro


In [ ]:
######################Still on While Loops
age = int(input('Enter your age: '))
while age <= 0:
  print("Age can't be less or equal to zero")
  age = int(input('Enter your age: '))
  print(f'You are {age} years old')


Enter your age: -1
Age can't be less or equal to zero
Enter your age: 0
You are 0 years old
Age can't be less or equal to zero
Enter your age: 47
You are 47 years old


In [ ]:
##################  USING THE WHILE NOT   ################
food = input("Enter the food you like(q to quit): ")
while not food =="q":
  print(f"You like {food}")
  food = input("Enter the food you like(q to quit): ")
  print("bye")


Enter the food you like(q to quit): Eba and Vegetable Soup
You like Eba and Vegetable Soup
Enter the food you like(q to quit): q
bye


In [ ]:
for n in range(1,6):
  print(2*n, end =" ")
  #print(',')

2 4 6 8 10 

In [ ]:
result = 0
for i in range(2,10):
  result += i
  print(i," print result",result)

2  print result 2
3  print result 5
4  print result 9
5  print result 14
6  print result 20
7  print result 27
8  print result 35
9  print result 44


In [39]:
j = int(input("Enter the age of a young adult: "))
while  j <= 5:
  print('NO')
  #j = int(input("Enter the age of a young adult: "))
else:
  print('Correct')

Streaming output truncated to the last 5000 lines.
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
NO
N

KeyboardInterrupt: ignored

In [ ]:
greeting = "HelLo!"
count = 0
for i in greeting:
  count += 1
  print(i)
  if count % 2 == 0:
   print(i)
print('done')

H
e
e
l
L
L
o
!
!
done


In [ ]:
x = ('Orange', 33, 1.5)
for i in x:
    print(i)


Orange
33
1.5


In [ ]:
nums = [12,16,18,25,26]
for number in nums:
  if number % 5 ==0:
   print(number)
   break
  else:
      print("Can't find a even number")

Can't find a even number
Can't find a even number
Can't find a even number
25


In [ ]:
##########  NESTED LOOPS EXAMPLEs ####################
for x in range(3):
    for y in range(1,10):
      print(y, end ="")
    print()

$$$$
$$$$
$$$$


In [ ]:
##########  NESTED LOOPS EXAMPLEs ####################
rows = int(input("Enter of rows to use: "))
columns = int(input("Enter of columns to use: "))
symbol  = input("Enter the type of symbol to use: ")

for x in range(rows):
    for y in range(columns):
      print(symbol, end ="      ")
    print()


Enter of rows to use: 4
Enter of columns to use: 3
Enter the type of symbol to use: %
%      %      %      
%      %      %      
%      %      %      
%      %      %      


In [ ]:
Mynum = float(input("Enter a number: "))
print('Your number is:',Mynum)

Enter a number: 12
Your number is: 12.0


In [ ]:
s = "azcbobobegghakl"
numVowels = 0
for char in s:
  if char =="a" or char =="e" or char =="o" or char =="u" or char =="i":
   numVowels += 1
print("No of vowels = " +str(numVowels))

No of vowels = 5


In [ ]:
s = "azcbobobegghakl"
numVowels = 0
for char in s:
  if char in "aeoui":
   numVowels += 1
print("No of vowels = " +str(numVowels))

No of vowels = 5


In [ ]:
s = "azcbobobegghakl"
len(s)

15

In [ ]:
########### The number of times bob occurs in azcbobobegghakl #############
s = "azcbobobegghakl"
substring = 'bob'
count = 0
for i in range(len(s) - len(substring) + 1):
    if s[i:i + len(substring)] == substring:
        count += 1
print("Number of times bob occurs is: ", count)

Number of times bob occurs is:  2


In [ ]:
###Write a program that prints the longest substring of s in which the letters occur in alphabetical order. For example, if s = 'azcbobobegghakl' ###

s = 'azcbobobegghakl'
current_substring = s[0]
longest_substring = s[0]
for char in s[1:]:
  if char >= current_substring[-1]:
    current_substring += char
  else:
      current_substring = char
  if len(current_substring) > len(longest_substring):
        longest_substring = current_substring
print("Longest substring in alphabetical order is:", longest_substring)


Longest substring in alphabetical order is: beggh


In [ ]:
s = 'azcbobobegghakl'
longest = 0
longestSubstring = ""
for a in range(1, len(s)):
  for char in range(len(s) + 1):
    substring = s[char: (char + a)]
    substringSort = "".join(sorted(substring))
    if substring == substringSort:
      if len(substring) > longest:
        longestSubstring = substring
        print('Longest substring in alphabetical order is: ' + str(longestSubstring))